require "user.packages"
require "user.colorscheme"
require "user.comment"
require "user.illuminate"
require "user.indentline"
require "user.keymaps"
require "user.lualine"
-- require "user.nvim-tree"
require "user.oil"
require "user.options"
require "user.telescope"
require "user.treesitter"
require "user.whichkey"
require "user.coc"

